#!/sbin/sh

. "$env"
[ -f $fstab ] || { print "Unable to find fstab!"; exit 1; }

sed -i "
	s/\b\(forceencrypt\|forcefdeorfbe\)=/encryptable=/g
" $fstab

if grep -q quota /$fstab; then
	print "Modified TWRP detected, enabling quota"
	if ! grep -q quota /$fstab; then
		sed -i "s/,quota//g" $fstab
	fi
fi

exit 0
