#!/sbin/sh

. "$env"

print "Disabling verification"
[ -f $fstab ] || { print "Unable to find fstab!"; exit 1; }

awk '
	$1 ~ /^\// {
		n = split($5, flags, ",")
		newflags=""
		for (i = 1; i <= n; i++) {
			if (flags[i] == "")
				continue
			if (flags[i] ~ /^verify/)
				continue
			if (flags[i] ~ /^support_scfs/)
				continue
			if (i > 1) newflags = newflags ","
			newflags = newflags flags[i]
		}
		if ($5 != newflags) $5 = newflags
		if ($5 == "") $5 = "defaults"
	}
	{ print }
' $fstab > fstabn
replace_file $fstab fstabn

setprop ro.config.dmverity false
rm -f verity_key sbin/firmware_key.cer

exit 0
