#!/sbin/sh

. "$env"

cat "$ramdisk_patch/$fstab" > "$ramdisk/$fstab"

if grep -qi GoogleWiz /system/build.prop; then
	print "GoogleWiz ROM detected, applying patches"
	cd "$tmp/minimal-patch"

	# fix permissions of patch files
	chmod -R 0755 .

	find -type f \( \
		-name "*.rc" ! -name "ueventd.*" \
		\) -exec chmod 0750 {} \;

	find -type f \( \
		-name "*.xml" -o -name "*.do" -o -name "*.pem" -o -name "*.vtab" -o \
		-name "fstab.*" -o -name "*.prop" -o -name "*_contexts" -o \
		-name "ueventd.*" -o -name "sepolicy" -o -name "sepolicy_version" \
		\) -exec chmod 0644 {} \;

	# default.prop
	setprop persist.security.ams.enforcing 1
	# fstab.samsungexynos8895
	sed -i '/HIDDEN/d' "$ramdisk/$fstab"
	sed -i '/MISC/d' "$ramdisk/$fstab"
	# init.container.rc, init.environ.rc, init.samsungexynos8895.rc
	cp -rf ./. "$ramdisk/"
	# init.samsungexynos8895.rc
	remove_service umount_service
	remove_service swapon

	# zzzfoobar66.rc: interferes with our settings, overrides iosched to noop
	# and more
	rm -f /system/etc/init/zzzfoobar66.rc
fi

cd "$ramdisk_patch" && [ "$(ls)" ] || exit 0

# fix permissions of patch files
chmod -R 0755 .

find -type f \( \
	-name "*.rc" ! -name "ueventd.*" \
	\) -exec chmod 0750 {} \;

find -type f \( \
	-name "*.xml" -o -name "*.do" -o -name "*.pem" -o -name "*.vtab" -o \
	-name "fstab.*" -o -name "*.prop" -o -name "*_contexts" -o \
	-name "ueventd.*" -o -name "sepolicy" -o -name "sepolicy_version" \
	\) -exec chmod 0644 {} \;

print "Copying new files"
cp -rd ./. "$ramdisk/"

import_rc init.velocity.rc
import_rc init.spectrum.rc

# clean up init from other kernels
rm -fr /system/etc/NOTO_LOGs
rm -f /system/bin/notorious.sh /system/bin/init.dalvik.sh /system/bin/init.selinux.sh

exit 0
