#!/sbin/sh

. "$env"

cd "$tmp/system" && [ "$(ls)" ] || exit 0

# fix permissions of vendor files
chmod -R 0755 .

find -type f \( \
	-name "*.bin" \
	\) -exec chmod 0664 {} \;

find -type f \( \
	-name "*.so" \
	\) -exec chmod 0644 {} \;

print "Copying new files to the system..."
cp -rd ./. "/system/"

exit 0
