#!/sbin/sh

. "$env"

cd "$tmp/system" && [ "$(ls)" ] || exit 0

# fix permissions of system files
chmod -R 0755 .

find -type f \( \
	-name "*.bin" \
	\) -exec chmod 0664 {} \;

find -type f \( \
	-name "*.so" \
	\) -exec chmod 0644 {} \;

cp -rd ./. "/system/"

print "Removing old Wi-Fi fix"
rm -fr "/system/etc/wifi"
rm -f "/system/vendor/etc/wifi/nvram_mfg.txt_r02j_b0" "/system/vendor/etc/wifi/nvram_net.txt_r02j_b0"

exit 0
